### ISSUE TITLE
jscolor-rails on heroku.  Getting 404 (Not Found) on png and gif files

### ISSUE THREAD

**Issue by chuckweinberger** [mwanji/jscolor-rails#1] opened 2013-01-18 03:32 UTC
I recently migrated my rails 3.0 app to 3.1.10.  I used jscolor.js with the 3.0 app, and was very happy with it.  

As part of the migration I added the jscolor-rails gem to my gemfile, made sure to add `//= require jscolor` to my application.js file, and removed the jscolor directory from my public directory.  I then ran bundle install.  

Everything works just fine on my development server, but when I push my code to Heroku, the server returns a code of 404(Not Found) on the gif and jpeg files.  Otherwise, jscolor still executes as expected (without the gif and jpegs, though).

Here's a screenshot of my gemfile.lock showing jscolor-rails.

![Screen Shot 2013-01-17 at 7 30 39 PM](https://f.cloud.github.com/assets/410847/77186/953cfa2e-611f-11e2-8686-eedb05118f9d.png)

Any idea why the jpg/gifs aren't loading?

**Comment by mwanji** [comment] 2013-01-18 06:47
Can you list the URLs that are 404'ing?

**Comment by chuckweinberger** [comment] 2013-01-18 16:49
Sure:

MYAPP.herokuapp.com/jscolor/cross.gif
MYAPP.herokuapp.com/jscolor/arrow.gif
MYAPP.herokuapp.com/jscolor/hs.png

**Comment by chuckweinberger** [comment] 2013-01-18 17:56
Here's a little more info that I've been able to uncover . . . 

If I set config.assets.debug to true in config/development.rb, then the gifs and the png load just fine.  That is the default setting in development.  If, however, I manually change the setting to false, relying on the Sprockets to concatenate my asset files like it does in production, then I get a 404.  See http://edgeguides.rubyonrails.org/asset_pipeline.html, section 3.1.

**Comment by mwanji** [comment] 2013-01-18 18:15
Is Heroku running in production or dev mode? Normally, when Sprockets can't
find an asset, it raises an exception.

Have you tried running locally in production mode?

You'll probably want to look at section 4 of the older guide, rather than
Edge: http://guides.rubyonrails.org/asset_pipeline.html

I'll try to reproduce this locally soon, I just haven't had a chance to set
up a test project yet.

**Comment by chuckweinberger** [comment] 2013-01-18 21:13
Heroku is running in production.  I just ran locally in production and experienced the same 404s on the three images.  

Thanks for taking a look at this.

**Comment by chuckweinberger** [comment] 2013-01-18 22:10
Think that I'm getting to the bottom of things, but I don't know how to fix it.  when running locally in production I first precompiled assets with bundle exec rake assets:precompile.  I also added config.serve_static_assets = true to my config/production.rb file.  Afterwards I confirmed that all three of the jscolor images were located in public/assets: 
![Screen Shot 2013-01-18 at 1 51 35 PM](https://f.cloud.github.com/assets/410847/79567/00789330-61ba-11e2-8aa4-421cb47815d5.png)

However, I'm still 404ing on URLs like: http://localhost:3000/jscolor/cross.gif.  Why is jscolor.js looking in the jscolor directory instead of the public/assets directory?

**Comment by mwanji** [comment] 2013-01-18 22:52
Thanks for the detective work, it set me on the right path.

It turns out jscolor.js tries to figure out the path to the images (cf.
getDir() and detectDir() on lines 37 and 46, respectively). Basically, it
tries to find the <script> tag that included jscolor.js and uses it to
build the url for the images. This works in dev mode, but in production
mode, there isn't a script tag for jscolor.js, so it falls back to
'jscolor/' and attempts to find images at jscolor/<img>.

I think that in both prod and dev modes, the images and JS will always be
accessible from the same root url, so modifying getDir() to fallback to '/'
instead of 'jscolor/' might be enough. I'll try that tomorrow.

Thanks again for your work!

**Comment by mwanji** [comment] 2013-01-20 22:00
Try the fix_dir branch to see if it works for you in dev and prod modes. If it does, I'll release the fix.

**Comment by chuckweinberger** [comment] 2013-01-20 23:40
Excellent!  All assets available in local development and production when using the fix-dir branch.  Also worked on my staging app, which is running on Heroku. 

Thanks so much for your help tracking/fixing this bug!

**Comment by mwanji** [comment] 2013-01-21 05:44
Awesome, thanks for your sleuthing!

**Comment by mwanji** [comment] 2013-01-21 07:40
Fixed in https://github.com/mwanji/jscolor-rails/commit/d7336d3aacca972a29c0df69e3a1f54056f3c4f1 and released as [v1.4.0.1](https://rubygems.org/gems/jscolor-rails).

**Closed as completed by mwanji** 2013-01-21 07:40 UTC
